# Generated by Django 2.0 on 2020-02-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detecting_id', models.IntegerField(blank=True, null=True, verbose_name='送检单号')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建订单时间')),
                ('patient', models.CharField(blank=True, max_length=20, null=True, verbose_name='受检者')),
                ('patient_condition', models.CharField(blank=True, max_length=200, null=True, verbose_name='患者情况')),
                ('order_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='订单类型')),
                ('product_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品名称')),
                ('sample_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='样本方式')),
                ('blood_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='血液类型')),
                ('quotation', models.FloatField(blank=True, null=True, verbose_name='产品价格')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='订单价格')),
                ('price_of_consulting', models.FloatField(blank=True, null=True, verbose_name='consulting')),
                ('collection', models.FloatField(blank=True, null=True, verbose_name='收款金额')),
                ('refund', models.FloatField(blank=True, null=True, verbose_name='退款金额')),
                ('collection_date', models.DateTimeField(blank=True, null=True, verbose_name='收款日期')),
                ('pay_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付方式')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注信息')),
                ('area', models.CharField(blank=True, max_length=10, null=True, verbose_name='大区')),
                ('area_manager', models.CharField(blank=True, max_length=10, null=True, verbose_name='大区经理')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='地区')),
                ('region_manager', models.CharField(blank=True, max_length=20, null=True, verbose_name='地区经理')),
                ('sale_person', models.CharField(blank=True, max_length=20, null=True, verbose_name='销售姓名')),
                ('hospital_region', models.CharField(blank=True, max_length=30, null=True, verbose_name='医院地区')),
                ('hospital', models.CharField(blank=True, max_length=50, null=True, verbose_name='医院')),
                ('doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name='送检医生')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='科室')),
                ('cancer', models.CharField(blank=True, max_length=20, null=True, verbose_name='癌种')),
                ('comes_from', models.CharField(blank=True, max_length=30, null=True, verbose_name='来源机构')),
                ('project_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='项目编号')),
                ('project_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='项目名称')),
                ('project_PI', models.CharField(blank=True, max_length=20, null=True, verbose_name='合作pi')),
                ('order_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='订单编号')),
                ('express_fee', models.FloatField(blank=True, null=True, verbose_name='快递费用')),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='支付单号')),
                ('sample_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='样本状态')),
                ('order_checking_status', models.CharField(blank=True, max_length=16, null=True, verbose_name='订单审核')),
                ('dry_ice_number', models.FloatField(blank=True, null=True, verbose_name='干冰数量')),
                ('dry_ice_fee', models.FloatField(blank=True, null=True, verbose_name='干冰费用')),
                ('express_order1', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮寄单号1')),
                ('express_date1', models.DateField(blank=True, null=True, verbose_name='邮寄日期1')),
                ('express_company1', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司1')),
                ('express_type1', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮寄类型1')),
                ('express_order2', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮寄单号2')),
                ('express_date2', models.DateField(blank=True, null=True, verbose_name='邮寄日期2')),
                ('express_company2', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司2')),
                ('express_type2', models.CharField(blank=True, max_length=200, null=True, verbose_name='邮寄类型2')),
                ('in_storage_time', models.DateField(blank=True, null=True, verbose_name='入库时间')),
                ('platform', models.CharField(blank=True, max_length=40, null=True, verbose_name='平台')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('detecting_id', 'create_date')},
        ),
    ]
