# Generated by Django 2.0 on 2020-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(upload_to='', verbose_name='销售数据文件')),
                ('upload_time', models.DateTimeField(auto_now=True, help_text='用户何时上传此文件', null=True, verbose_name='上传时间')),
            ],
        ),
    ]
