# Generated by Django 2.0 on 2020-02-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200215_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='area',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='大区'),
        ),
        migrations.AddField(
            model_name='orders',
            name='area_manager',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='大区经理'),
        ),
        migrations.AddField(
            model_name='orders',
            name='blood_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='血液类型'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cancer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='癌种'),
        ),
        migrations.AddField(
            model_name='orders',
            name='collection',
            field=models.FloatField(blank=True, null=True, verbose_name='收款金额'),
        ),
        migrations.AddField(
            model_name='orders',
            name='collection_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收款日期'),
        ),
        migrations.AddField(
            model_name='orders',
            name='comes_from',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='来源机构'),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='orders',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='科室'),
        ),
        migrations.AddField(
            model_name='orders',
            name='detecting_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='送检单号'),
        ),
        migrations.AddField(
            model_name='orders',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='送检医生'),
        ),
        migrations.AddField(
            model_name='orders',
            name='dry_ice_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='干冰费用'),
        ),
        migrations.AddField(
            model_name='orders',
            name='dry_ice_number',
            field=models.FloatField(blank=True, null=True, verbose_name='干冰数量'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_company1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司1'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_company2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司2'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_date1',
            field=models.DateField(blank=True, null=True, verbose_name='邮寄日期1'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_date2',
            field=models.DateField(blank=True, null=True, verbose_name='邮寄日期2'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='快递费用'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_order1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='邮寄单号1'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_order2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='邮寄单号2'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_type1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='邮寄类型1'),
        ),
        migrations.AddField(
            model_name='orders',
            name='express_type2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='邮寄类型2'),
        ),
        migrations.AddField(
            model_name='orders',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='医院'),
        ),
        migrations.AddField(
            model_name='orders',
            name='hospital_region',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='医院地区'),
        ),
        migrations.AddField(
            model_name='orders',
            name='in_storage_time',
            field=models.DateField(blank=True, null=True, verbose_name='入库时间'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_checking_status',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='订单审核'),
        ),
        migrations.AddField(
            model_name='orders',
            name='patient_condition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='患者情况'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pay_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='支付单号'),
        ),
        migrations.AddField(
            model_name='orders',
            name='platform',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='orders',
            name='price_of_consulting',
            field=models.FloatField(blank=True, null=True, verbose_name='consulting'),
        ),
        migrations.AddField(
            model_name='orders',
            name='project_PI',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='合作pi'),
        ),
        migrations.AddField(
            model_name='orders',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='orders',
            name='project_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='orders',
            name='refund',
            field=models.FloatField(blank=True, null=True, verbose_name='退款金额'),
        ),
        migrations.AddField(
            model_name='orders',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='orders',
            name='region_manager',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='地区经理'),
        ),
        migrations.AddField(
            model_name='orders',
            name='sale_person',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='销售姓名'),
        ),
        migrations.AddField(
            model_name='orders',
            name='sample_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='样本状态'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建订单时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='订单编号'),
        ),
    ]
