# Generated by Django 2.0 on 2020-02-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200215_0431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('detecting_id', 'create_date')},
        ),
    ]
