# Generated by Django 2.0 on 2020-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200215_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='detecting_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='送检单号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='detecting_id_bk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='单号'),
        ),
    ]
