# Generated by Django 2.0 on 2020-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200215_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='in_storage_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间'),
        ),
    ]
