# Generated by Django 2.0 on 2020-02-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200215_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='express_date1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='邮寄日期1'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='express_date2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='邮寄日期2'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='in_storage_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='入库时间'),
        ),
    ]
